name: Pull Request Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  # pypi-publish:
  #   name: Publish release to PyPI
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: pypi
  #     url: https://pypi.org/p/phantom-core
  #   permissions:
  #     id-token: write

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.x"

  #     - name: Install Poetry
  #       run: pipx install poetry

  #     - name: Print package version
  #       run: |
  #         poetry version

  #     - name: Build package
  #       run: |
  #         poetry build --no-interaction --no-ansi

  #     - name: Publish package distributions to PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1

  ValidateVersion:
    name: Validate Package Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get package version from pyproject.toml
        id: version
        run: |
          VERSION=$(poetry version -s)
          echo "Found version: ${VERSION}"
          echo "version=v${VERSION}" >> $GITHUB_OUTPUT
